app/routes.php
<?php

Route::group(array('prefix' => 'admin', 'before' => 'admin'), function(){
    Route::resource('users', 'AdminUsersController', array('except' => array('show')));
    Route::resource('contents', 'AdminContentsController', array('except' => array('show','index')));

    Route::resource('assessments', 'AdminAssessmentsController', array('except' => array('show')));

    Route::resource('medicals', 'AdminMedicalsController', array('except' => array('show')));

    Route::resource('schedules', 'AdminSchedulesController', array('except' => array('show','edit','update')));

	Route::get('news', array('as' => 'admin.news', 'uses' => 'AdminContentsController@getNews'));
    Route::get('tips', array('as' => 'admin.tips', 'uses' => 'AdminContentsController@getTips'));

    Route::get('users/assesslist', array('as' => 'admin.getAssessList', 'uses' => 'AdminUsersController@getAssessList'));

    //Route::get('users/addassessmentperuser', array('as' => 'admin.addassessperuser', 'uses' => 'AdminUsersController@addassessmentperuser'));



    Route::get('users/adduserassesments', array('as' => 'admin.getNewAsess', 'uses' => 'AdminUsersController@getNewAsess'));
    Route::post('users/adduserassesments', array('as' => 'admin.postNewAsess', 'uses' => 'AdminUsersController@postNewAsess'));


    Route::get('users/edituassess', array('as' => 'admin.editAsess', 'uses' => 'AdminUsersController@geteditAsessbyDate'));
    Route::post('users/edituassess', array('as' => 'admin.editAsess', 'uses' => 'AdminUsersController@posteditAsessbyDate'));

    Route::post('users/deluassess', array('as' => 'admin.delAsess', 'uses' => 'AdminUsersController@delAsessbyDate'));

    //Route::resource('userassessment', 'AdminUsersAssessmentsController', array('except' => array('show')));



});


Route::group(array('prefix' => 'admin'), function(){

    Route::post('users/addassessmentperuser', array('as' => 'admin.addassessperuser', 'uses' => 'AdminUsersController@addassessmentperuser'));

    Route::get('login', array( 'as' => 'admin.login',  'uses' => 'AdminAuthController@getLogin'));
    Route::post('login', array('as' => 'admin.login.post', 'uses' => 'AdminAuthController@postLogin'));
    Route::get('logout', array( 'as' => 'admin.logout', 'uses' => 'AdminAuthController@getLogout'));


});


Route::group(array('prefix' => 'service'), function(){

    Route::get('login', array( 'uses' => 'ServiceAuthController@getLogin'));
    Route::post('login', array( 'as' => 'service.login.post','uses' => 'ServiceAuthController@postLogin'));
    
    Route::get('users/medicallist', array( 'uses' => 'ServiceUsersController@medicallist'));

    Route::post('register', array( 'as' => 'service.login.post','uses' => 'ServiceAuthController@postRegister'));



    //Route::get('news/findtips', array( 'uses' => 'ServiceUsersController@findtips'));

    //Route::post('news/findtips', array( 'uses' => 'ServiceUsersController@findtips'));


   

    

});

Route::group(array('prefix' => 'service' , 'before' => 'service'), function(){

    Route::get('news/display', array( 'uses' => 'ServiceUsersController@findnews'));

    Route::get('news/details/{news_id}', array( 'uses' => 'ServiceUsersController@newsdetails'));

    Route::get('news/findtips', array( 'uses' => 'ServiceUsersController@findtips'));
   

    Route::get('schedules/getreschedule/{userName}', array( 'uses' => 'ServiceSchedulesController@getreschedule'));

   Route::get('logout', array( 'uses' => 'ServiceAuthController@getLogout'));

   Route::get('users/assessmentlist', array( 'uses' => 'ServiceUsersController@assessmentlist'));

   Route::get('users/assessmentcurvedata/{assessmentId}/{userId}', array( 'uses' => 'ServiceUsersController@assessmentcurvedata'));

   Route::get('users/profilemedical', array( 'uses' => 'ServiceUsersController@profilemedical'));

   Route::post('users/updateprofile', array( 'uses' => 'ServiceUsersController@updateprofile'));




});

// Route::group(array('prefix' => 'admin', 'before' => 'auth'), function(){
//     Route::resource('posts', 'AdminPostsController', array('except' => array('show')));
// });

// Route::get('/', array('as' => 'home', 'uses' => 'PostsController@getIndex'));
// Route::get('post/{id}', array('as' => 'post', 'uses' => 'PostsController@getPost'))->where('id', '[1-9][0-9]*');

app/models/Assessment.php
<?php

class Assessment extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		'name' => 'required',
		'unit' => 'required',
	];

	// Don't forget to fill this array
	protected $fillable = ['name','unit'];

	public function users() {

		return $this->belongsToMany('User')->withPivot('assessment','assessment_date','assessment_time');	
	}

	public static function allPaginate($perPage=5){

		 $users = Assessment::orderBy('created_at', 'DESC')
		 				->paginate($perPage);

        return $users;


	}


}

app/views/Admin/assessments/create.blade.php
@extends('_layouts.default')

@section('content')
<div class="users form">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>Add Assessment</h1>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-3">
			<div class="actions">
				<div class="panel panel-default">
					<div class="panel-heading">Actions</div>
						<div class="panel-body">
							<ul class="nav nav-pills nav-stacked">

								<li>
									<a href="{{route('admin.assessments.index')}}">
										<span class="glyphicon glyphicon-list"></span>&nbsp;&nbsp;List Assessment</a>
								</li>					
							</ul>
						</div>
					</div>
				</div>			
		</div>{{-- end col md 3 --}}
		<div class="col-md-9">
			<div>
				 @if(Session::get('errors'))
                        <div class="alert alert-danger alert-dismissable">
                             @foreach($errors->all('<p>:message</p>') as $message)
                                {{$message}}
                             @endforeach
                        </div>
                    @endif
			</div>
			{{ Form::open(array('route' => 'admin.assessments.store')) }}
			    @include('admin.assessments._partials.form')
			{{ Form::close() }}
		</div>{{-- end col md 12 --}}
	</div>{{-- end row --}}
</div>
@stop

app/views/Admin/assessments/edit.blade.php
@extends('_layouts.default')

@section('content')
<div class="users form">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>Edit Assessment</h1>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-3">
			<div class="actions">
				<div class="panel panel-default">
					<div class="panel-heading">Actions</div>
						<div class="panel-body">
							<ul class="nav nav-pills nav-stacked">

								<li>
									{{ Form::open(array('route' => array('admin.assessments.destroy', $assessment->id), 'method' => 'delete', 'class' => 'destroy')) }}
						            <span class="glyphicon glyphicon-remove"></span>
						            {{ Form::submit('DELETE') }}
						            {{ Form::close() }}
								</li>

								<li>
									<a href="{{route('admin.assessments.index')}}">
										<span class="glyphicon glyphicon-list"></span>&nbsp;&nbsp;List Assessments</a>

								</li>					
							</ul>
						</div>
					</div>
				</div>			
		</div>{{-- end col md 3 --}}
		<div class="col-md-9">
			<div>
				 @if(Session::get('errors'))
                        <div class="alert alert-danger alert-dismissable">
                             @foreach($errors->all('<p>:message</p>') as $message)
                                {{$message}}
                             @endforeach
                        </div>
                    @endif
			</div>
    		{{ Form::model($assessment, array('route' => array('admin.assessments.update', $assessment->id), 'method' => 'put')) }}
			    @include('admin.assessments._partials.form')
			{{ Form::close() }}
		</div>{{-- end col md 12 --}}
	</div>{{-- end row --}}
</div>
@stop

app/views/Admin/assessments/index.blade.php
@extends('_layouts.default')

@section('content')

<div class="users index">

	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>Assessment List</h1>
			</div>
		</div>{{-- end col md 12 --}}
	</div>{{-- end row --}}

	<div class="row">
		<div class="col-md-3">
			<div class="actions">
				<div class="panel panel-default">
					<div class="panel-heading">Actions</div>
						<div class="panel-body">
							<ul class="nav nav-pills nav-stacked">
								<li>
									<a href="{{route('admin.assessments.create')}}">
										<span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;New Assessment</a>
								</li>
							</ul>
						</div>{{-- end body --}}
				</div>{{-- end panel --}}
			</div>{{-- end actions --}}
		</div>{{-- end col md 3 --}}

		<div class="col-md-9">
			<table cellpadding="0" cellspacing="0" class="table table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Unit</th>
					<th class="actions">Actions</th>
				</tr>
			</thead>
			<tbody>

	@foreach($assessments as $assessment)
	<tr>
		<td>{{$assessment->name}}</td>
		<td>{{$assessment->unit}}</td>
		<td class="actions">
			<a href="{{route('admin.assessments.edit', array($assessment->id))}}"><span class="glyphicon glyphicon-edit"></span></a>
			{{ Form::open(array('route' => array('admin.assessments.destroy', $assessment->id), 'method' => 'delete', 'class' => 'destroy')) }}
            {{ Form::submit('X' , array('class' => "glyphicon glyphicon-remove")) }}
            {{ Form::close() }}
		</td>
	</tr>
	@endforeach
	</tbody>
</table>

			
		</div> {{-- end col md 9 --}}
	</div>{{-- end row --}}

	<div>{{ $assessments->links() }}</div>
</div>{{-- end containing of content --}}
@stop

app/views/Admin/assessments/show.blade.php
C:\xampp\htdocs\larafitness\app/views/assessments/show.blade.php