app/routes.php
<?php

Route::group(array('prefix' => 'admin', 'before' => 'admin'), function(){
    Route::resource('users', 'AdminUsersController', array('except' => array('show')));
    Route::resource('contents', 'AdminContentsController', array('except' => array('show','index')));

    Route::resource('assessments', 'AdminAssessmentsController', array('except' => array('show')));

    Route::resource('medicals', 'AdminMedicalsController', array('except' => array('show')));

    Route::resource('schedules', 'AdminSchedulesController', array('except' => array('show','edit','update')));

	Route::get('news', array('as' => 'admin.news', 'uses' => 'AdminContentsController@getNews'));
    Route::get('tips', array('as' => 'admin.tips', 'uses' => 'AdminContentsController@getTips'));

    Route::get('users/assesslist', array('as' => 'admin.getAssessList', 'uses' => 'AdminUsersController@getAssessList'));

    //Route::get('users/addassessmentperuser', array('as' => 'admin.addassessperuser', 'uses' => 'AdminUsersController@addassessmentperuser'));



    Route::get('users/adduserassesments', array('as' => 'admin.getNewAsess', 'uses' => 'AdminUsersController@getNewAsess'));
    Route::post('users/adduserassesments', array('as' => 'admin.postNewAsess', 'uses' => 'AdminUsersController@postNewAsess'));


    Route::get('users/edituassess', array('as' => 'admin.editAsess', 'uses' => 'AdminUsersController@geteditAsessbyDate'));
    Route::post('users/edituassess', array('as' => 'admin.editAsess', 'uses' => 'AdminUsersController@posteditAsessbyDate'));

    Route::post('users/deluassess', array('as' => 'admin.delAsess', 'uses' => 'AdminUsersController@delAsessbyDate'));

    //Route::resource('userassessment', 'AdminUsersAssessmentsController', array('except' => array('show')));



});


Route::group(array('prefix' => 'admin'), function(){

    Route::post('users/addassessmentperuser', array('as' => 'admin.addassessperuser', 'uses' => 'AdminUsersController@addassessmentperuser'));

    Route::get('login', array( 'as' => 'admin.login',  'uses' => 'AdminAuthController@getLogin'));
    Route::post('login', array('as' => 'admin.login.post', 'uses' => 'AdminAuthController@postLogin'));
    Route::get('logout', array( 'as' => 'admin.logout', 'uses' => 'AdminAuthController@getLogout'));


});


Route::group(array('prefix' => 'service'), function(){

    Route::get('login', array( 'uses' => 'ServiceAuthController@getLogin'));
    Route::post('login', array( 'as' => 'service.login.post','uses' => 'ServiceAuthController@postLogin'));
    
    Route::get('users/medicallist', array( 'uses' => 'ServiceUsersController@medicallist'));

    Route::post('register', array( 'as' => 'service.login.post','uses' => 'ServiceAuthController@postRegister'));



    //Route::get('news/findtips', array( 'uses' => 'ServiceUsersController@findtips'));

    //Route::post('news/findtips', array( 'uses' => 'ServiceUsersController@findtips'));


   

    

});

Route::group(array('prefix' => 'service' , 'before' => 'service'), function(){

    Route::get('news/display', array( 'uses' => 'ServiceUsersController@findnews'));

    Route::get('news/details/{news_id}', array( 'uses' => 'ServiceUsersController@newsdetails'));

    Route::get('news/findtips', array( 'uses' => 'ServiceUsersController@findtips'));
   

    Route::get('schedules/getreschedule/{userName}', array( 'uses' => 'ServiceSchedulesController@getreschedule'));

   Route::get('logout', array( 'uses' => 'ServiceAuthController@getLogout'));

   Route::get('users/assessmentlist', array( 'uses' => 'ServiceUsersController@assessmentlist'));

   Route::get('users/assessmentcurvedata/{assessmentId}/{userId}', array( 'uses' => 'ServiceUsersController@assessmentcurvedata'));

   Route::get('users/profilemedical', array( 'uses' => 'ServiceUsersController@profilemedical'));

   Route::post('users/updateprofile', array( 'uses' => 'ServiceUsersController@updateprofile'));




});

// Route::group(array('prefix' => 'admin', 'before' => 'auth'), function(){
//     Route::resource('posts', 'AdminPostsController', array('except' => array('show')));
// });

// Route::get('/', array('as' => 'home', 'uses' => 'PostsController@getIndex'));
// Route::get('post/{id}', array('as' => 'post', 'uses' => 'PostsController@getPost'))->where('id', '[1-9][0-9]*');

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	 public static $rules = [
        'username' => 'required|email',
        'password' => 'required'
    ];

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password');

	// Don't forget to fill this array
	protected $fillable = ['username', 'password', 'token'];

	 public function profile()
    {
        return $this->hasOne('Profile');
    }

    public function medical() {

		return $this->belongsToMany('Medical');	
	}


	public function assessments() {

		return $this->belongsToMany('Assessment')->withPivot('assessment','assessment_date','assessment_time');	
	}

	
	public static function allPaginate($perPage=5){

		 $users = User::where('is_admin', '!=', 1)
		 				->orderBy('created_at', 'DESC')
		 				->paginate($perPage);

        return $users;


	}


	/**
	 * Check user's permissions
	 *
	 * @return bool
	 */
	public function isAdmin()
	{
		return ($this->is_admin == true);
	}

}

app/views/Admin/users/adduserassesments.blade.php
@extends('_layouts.default')

@section('content')
<div class="users form">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>Add Assessment</h1>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-3">
			<div class="actions">
				<div class="panel panel-default">
					<div class="panel-heading">Actions</div>
						<div class="panel-body">
							<ul class="nav nav-pills nav-stacked">

								<li>
									<a href="{{route('admin.getAssessList')}}">
										<span class="glyphicon glyphicon-list"></span>&nbsp;&nbsp;List Assessment</a>
								</li>					
							</ul>
						</div>
					</div>
				</div>			
		</div>{{-- end col md 3 --}}
		<div class="col-md-9">
			<div>
				 @if(Session::get('errors'))
                        <div class="alert alert-danger alert-dismissable">
                             @foreach($errors->all('<p>:message</p>') as $message)
                                {{$message}}
                             @endforeach
                        </div>
                    @endif
			</div>


			{{ Form::open(array('route' => 'admin.postNewAsess' , "onsubmit" => "return validateForm()", 
					  "id" => "setAssessmentUser")) }}

				@if( isset($tabinfo) )

					{{Form::hidden('old_date',$assess_date)}}
					{{Form::hidden('old_time',$assess_time)}}
					
					 @include('admin.users._partials.assessform',
					 	array('tabinfo'=>$tabinfo,'assess_time'=>$assess_time,
					 			'assess_date'=>$assess_date,'userlist' =>$userlist
					 	))

				@else
					 @include('admin.users._partials.assessform')
				@endif
				
			{{ Form::close() }}
		</div>{{-- end col md 12 --}}
	</div>{{-- end row --}}
</div>
<script>
  $(function() {
  	$('#datepicker').datepicker();
  	$('#timepicker').timepicker({minuteGrid: 15});

  	$('#forAssessmentSave').hide();

  	$( "#addUser" ).click(function(event) {
		event.preventDefault();
		//alert('hi');
		submitForm("#setUserForAssessment");
	});


$(document).on('click', '.remove-td', function(event){

		$(this).parent().parent().remove();

		var item = $(this).data( "role" );

		var index = userArray.indexOf(item);

		if (index > -1) {
		    userArray.splice(index, 1);
		}

});
	

	$(document).on('click', '#setuser', function(event){ 

		

		//event.preventDefault();
		var userId = $(this).prev().val();
		//alert(userId); die();
		if(userId){
			$('#result').hide();	
			var getaddress_url = adminURL + "users/addassessmentperuser";

            $.post( getaddress_url , { userId : userId } ,callbackassessment);
		}
		else{
		  $('#result').html('Please add user to continue!');
		  $('#result').addClass('err');
		  return false;
		}
		

	});

  });
  <?php 

  	  if(isset($userlist)){
  	  	echo 'var userArray = ['.implode(',', array_keys($userlist) ).'];';
  	  } else {
  	  		echo 'var userArray = new Array();';
  	  }

   ?>
 
  function callbackassessment(data){

  				var item = data;
				var len = item.assessment.length;
				var users_data = item.user;
				var assessment_data =item.assessment;
				var assessment_unit_data = [];
                var txt = "";
                var txt1 = "";
                var txt2 = "";
                var username = users_data.username.split("@");
                username = username[0];
                var userid = users_data.id;

                if( jQuery.inArray(userid, userArray)===-1 && len){

                	userArray.push(userid);

                		txt1 += '<tr><td>'+username+'</td>';
                		
                    		for(var i=0;i<len;i++){	

	                    			
	                    			txt2 += '<td><input type="text" class="assessmentList" name="data[A-'+assessment_data[i].id+'][U-'+userid+']" placeholder="No..." />'+assessment_data[i].unit+'</td>'; 
	                    		}
	                  
	                  		txt2 += "<td><button class='remove-td' data-role='"+userid+"'>X</button></td>";	
	                    	txt+= txt1+txt2;
	                  
                    	if(txt != ""){
                        	$("#assessmentTable").append(txt);
                    	}
                
                    }
                    //$('#forAssessmentEdit').hide();
                    $('#forAssessmentSave').show();
	}

	// form validation added
	function validateForm()
	{
	var x=$('#datepicker').val();
	var y=$('#timepicker').val();
	if (x=="" || y=="")
	  {
	  	$('#result').show();
	  $('#result').html('Please fill date and time to add assessment!');
	  $('#result').addClass('err');
	  return false;
	  }
	}
 </script>
@stop

app/views/Admin/users/assessmentslist.blade.php
@extends('_layouts.default')

@section('content')

<div class="users index">

	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>Users Assessment</h1>
			</div>
		</div>{{-- end col md 12 --}}
	</div>{{-- end row --}}

	<div class="row">
		<div class="col-md-3">
			<div class="actions">
				<div class="panel panel-default">
					<div class="panel-heading">Actions</div>
						<div class="panel-body">
							<ul class="nav nav-pills nav-stacked">
								<li>
									<a href="{{route('admin.getNewAsess')}}">
										<span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;New Assessments</a>
								</li>
							</ul>
						</div>{{-- end body --}}
				</div>{{-- end panel --}}
			</div>{{-- end actions --}}
		</div>{{-- end col md 3 --}}

		<div class="col-md-9">
			<table cellpadding="0" cellspacing="0" class="table table-striped">
				<thead>
					<tr>
			<th>Assessment Date</th>
			<th>Time</th>
			<th class="actions">Actions</th>
	</tr>
	</thead>
	<tbody>
	@foreach($result as $value)
	<tr>
		<td>{{$value->assessment_date}}</td>
		<td>{{substr($value->assessment_time, 0, 5)}}</td>
		<td class="actions">

			{{ Form::open(array('route' => array('admin.editAsess'), 'method' => 'post', 'class' => 'destroy')) }}
            {{Form::hidden('assess_date',$value->assessment_date);}}
            {{Form::hidden('assess_time',$value->assessment_time);}}
            {{ Form::submit('EDIT' , array('class' => "glyphicon glyphicon-remove")) }}
            {{ Form::close() }} |
            {{ Form::open(array('route' => array('admin.delAsess'), 'method' => 'post', 'class' => 'destroy')) }}
            {{Form::hidden('assess_date',$value->assessment_date);}}
            {{Form::hidden('assess_time',$value->assessment_time);}}
	        {{ Form::submit('DEL' , array('class' => "glyphicon glyphicon-remove")) }}
            {{ Form::close() }}
            
		</td>
	</tr>
	@endforeach
	</tbody>
</table>
		
		</div> {{-- end col md 9 --}}
	</div>{{-- end row --}}

</div>{{-- end containing of content --}}
@stop

app/views/Admin/users/create.blade.php
@extends('_layouts.default')

@section('content')
<div class="users form">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>Add User</h1>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-3">
			<div class="actions">
				<div class="panel panel-default">
					<div class="panel-heading">Actions</div>
						<div class="panel-body">
							<ul class="nav nav-pills nav-stacked">

								<li>
									<a href="{{route('admin.users.index')}}">
										<span class="glyphicon glyphicon-list"></span>&nbsp;&nbsp;List Users</a>
								</li>					
							</ul>
						</div>
					</div>
				</div>			
		</div>{{-- end col md 3 --}}
		<div class="col-md-9">
			<div>
				 @if(Session::get('errors'))
                        <div class="alert alert-danger alert-dismissable">
                             @foreach($errors->all('<p>:message</p>') as $message)
                                {{$message}}
                             @endforeach
                        </div>
                    @endif
			</div>
			{{ Form::open(array('route' => 'admin.users.store')) }}
			    @include('admin.users._partials.form')
			{{ Form::close() }}
		</div>{{-- end col md 12 --}}
	</div>{{-- end row --}}
</div>
@stop

app/views/Admin/users/edit.blade.php
@extends('_layouts.default')

@section('content')
<div class="users form">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>Edit User</h1>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-3">
			<div class="actions">
				<div class="panel panel-default">
					<div class="panel-heading">Actions</div>
						<div class="panel-body">
							<ul class="nav nav-pills nav-stacked">

								<li>
									{{ Form::open(array('route' => array('admin.users.destroy', $user->id), 'method' => 'delete', 'class' => 'destroy')) }}
						            <span class="glyphicon glyphicon-remove"></span>
						            {{ Form::submit('DELETE') }}
						            {{ Form::close() }}
								</li>

								<li>
									<a href="{{route('admin.users.index')}}">
										<span class="glyphicon glyphicon-list"></span>&nbsp;&nbsp;List Users</a>

								</li>					
							</ul>
						</div>
					</div>
				</div>			
		</div>{{-- end col md 3 --}}
		<div class="col-md-9">
			<div>
				 @if(Session::get('errors'))
                        <div class="alert alert-danger alert-dismissable">
                             @foreach($errors->all('<p>:message</p>') as $message)
                                {{$message}}
                             @endforeach
                        </div>
                    @endif
			</div>
			<ul class="nav nav-tabs" id="myTab">
			  <li class=""><a data-toggle="tab" href="#profile">Profile Info</a></li>
			  <li class="active"><a data-toggle="tab" href="#medicalinfo">Medical Info</a></li>
			</ul>
    		{{ Form::open( array('route' => array('admin.users.update', $user->id), 'method' => 'put')) }}
			    @if( $user->profile )
					
					{{Form::hidden('profile[id]',$user->profile->id)}}
					
					 @include('admin.users._partials.form',
					 	array(

					 			'profile' => $user->profile,
					 			'medi_id' => $medi_id
					 	))

					@else
					 @include('admin.users._partials.form' ,array('medi_id' => $medi_id))
					@endif

				

			{{ Form::close() }}
		</div>{{-- end col md 12 --}}
	</div>{{-- end row --}}
</div>
@stop

app/views/Admin/users/index.blade.php
@extends('_layouts.default')

@section('content')

<div class="users index">

	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>Users Assessment</h1>
			</div>
		</div>{{-- end col md 12 --}}
	</div>{{-- end row --}}

	<div class="row">
		<div class="col-md-3">
			<div class="actions">
				<div class="panel panel-default">
					<div class="panel-heading">Actions</div>
						<div class="panel-body">
							<ul class="nav nav-pills nav-stacked">
								<li>
									<a href="{{route('admin.users.create')}}">
										<span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;New User</a>
								</li>
							</ul>
						</div>{{-- end body --}}
				</div>{{-- end panel --}}
			</div>{{-- end actions --}}
		</div>{{-- end col md 3 --}}

		<div class="col-md-9">
			<table cellpadding="0" cellspacing="0" class="table table-striped">
				<thead>
					<tr>
			<th>User</th>
			<th>Joining Date</th>
			<th class="actions">Actions</th>
	</tr>
	</thead>
	<tbody>

	@foreach($users as $user)
	<tr>
		<td>{{$user->username}}</td>
		<td>{{$user->created_at}}</td>
		<td class="actions">
			<a href="{{route('admin.users.edit', array($user->id))}}"><span class="glyphicon glyphicon-edit"></span></a>
			{{ Form::open(array('route' => array('admin.users.destroy', $user->id), 'method' => 'delete', 'class' => 'destroy')) }}
            {{ Form::submit('X' , array('class' => "glyphicon glyphicon-remove")) }}
            {{ Form::close() }}
		</td>
	</tr>
	@endforeach
	</tbody>
</table>

			
		</div> {{-- end col md 9 --}}
	</div>{{-- end row --}}

	<div>{{ $users->links() }}</div>
</div>{{-- end containing of content --}}
@stop

app/views/Admin/users/show.blade.php
C:\xampp\htdocs\larafitness\app/views/users/show.blade.php